// Generated by CoffeeScript 1.6.3
RigorixServices.factory("AuthService", function($resource) {
  return $resource(RigorixEnv.API_DOMAIN + "auth/:id_utente/:action/:value", {
    id_utente: User.id_utente,
    action: "@action",
    value: "@value",
    isArray: true
  });
});
