// Generated by CoffeeScript 1.6.3
RigorixServices.factory("SfideService", function($resource) {
  return $resource(RigorixEnv.API_DOMAIN + "sfide/:filter/:value", {
    filter: "@filter",
    value: "@value",
    isArray: true
  }, {
    getArchivioSfide: {
      method: 'GET',
      isArray: true,
      params: {
        filter: 'archivio',
        value: User.id_utente
      }
    },
    getSfidePending: {
      method: 'GET',
      isArray: true,
      params: {
        filter: 'pending',
        value: User.id_utente
      }
    }
  });
});
