// Generated by CoffeeScript 1.6.3
var Rigorix, RigorixServices, SocialLoginUrl;

Rigorix = angular.module("Rigorix", ["ngRoute", "RigorixServices"]);

RigorixServices = angular.module("RigorixServices", ["ngResource"]);

SocialLoginUrl = "http://tre.rigorix.com/social_login.php";

Rigorix.config(function($routeProvider) {
  $routeProvider.when("/", {
    templateUrl: "app/templates/home.page.html",
    controller: "Home"
  });
  $routeProvider.when("/home", {
    templateUrl: "app/templates/home.page.html",
    controller: "Home"
  });
  $routeProvider.when("/logout", {
    templateUrl: "app/templates/home.page.html",
    controller: "Home"
  });
  $routeProvider.when("/area-personale", {
    templateUrl: "app/templates/area-personale/page.html",
    controller: "AreaPersonale"
  });
  $routeProvider.when("/area-personale/:section", {
    templateUrl: "app/templates/area-personale/page.html",
    controller: "AreaPersonale"
  });
  $routeProvider.when("/area-personale/:section/:sectionPage", {
    templateUrl: "app/templates/area-personale/page.html",
    controller: "AreaPersonale"
  });
  $routeProvider.when("/regolamento", {
    templateUrl: "app/templates/regolamento.page.html"
  });
  $routeProvider.when("/riconoscimenti", {
    templateUrl: "app/templates/riconoscimenti.page.html"
  });
  $routeProvider.when("/partners", {
    templateUrl: "app/templates/partners.page.html"
  });
  return $routeProvider.otherwise({
    templateUrl: "app/templates/lost.html"
  });
});
