// Generated by CoffeeScript 1.6.3
var app, express, fs, http, path;

express = require('express');

http = require('http');

path = require('path');

fs = require('fs');

app = express();

app.set("port", process.env.port);

app.use(express["static"](path.join(__dirname, '/')));

app.use(express.favicon());

app.get("/", function(req, res) {
  return res.render('index', req);
});

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});
