// Generated by CoffeeScript 1.6.3
var Terminal;

Terminal = {
  serviceUrl: "service.php",
  collector: [],
  collectorPointer: 0,
  console: $("#jsterminal-code"),
  commandLine: $("#jsterminal-line"),
  init: function() {
    return this.commandLine.on("keydown", function(e) {
      return Terminal.keyboardMap.execute.call(this, e);
    });
  }
};
