<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Wednesday 16th of January 2013 05:42:45 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------
$env = json_decode(file_get_contents($_SERVER['DOCUMENT_ROOT'] . '/.env'));
return
	array(
		"base_url" => $env->HYBRIDAUTH_URL, //"http://tre.rigorix.com/hybridauth/",

		"providers" => array (
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array (
				"enabled" => false
			),

			"Yahoo" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "373679399934.apps.googleusercontent.com", "secret" => "3x0YjUyBsRH_DJ1cdbuEircN" )
			),

			"Facebook" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "208222219208475", "secret" => "f1f51dbd33c7d16697d08cfad39fb87d" )
			),

			"Twitter" => array (
				"enabled" => true,
				"keys"    => array ( "key" => "v2L3r7wXvYTTNLNonWgg", "secret" => "sEokdAWWYSaVlFrZfcdvL6AxthJf79TmoknTNsTHA" )
			),

			// windows live
			"Live" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"MySpace" => array (
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" )
			),

			"LinkedIn" => array (
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" )
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "V5UUIHGHLIAGQRDFJ5MRYFXH3ASMGW2INKPBOPR0IR0CKMD4", "secret" => "SQQWL0HVQKMUONMDT50KXT2ZAXV2KEWZISRBK3EJDJI51BZS" )
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
