// Generated by CoffeeScript 1.6.3
Rigorix.filter("capitalize", function() {
  return function(input, scope) {
    return input.substring(0, 1).toUpperCase() + input.substring(1);
  };
});

Rigorix.filter("varToTitle", function() {
  return function(input, scope) {
    input = input.split("_").join(" ");
    return input.substring(0, 1).toUpperCase() + input.substring(1);
  };
});

Rigorix.filter("stringToDate", function() {
  return function(input, scope) {
    var date;
    date = new Date(input);
    return date;
  };
});
