// Generated by CoffeeScript 1.6.3
Rigorix.controller("Home", function($scope, UserService) {
  var _this = this;
  $scope.updateResources = function() {
    $scope.campione = UserService.getCampioneSettimana();
    return $scope.activeUsers = UserService.getActiveUsers();
  };
  $scope.updateResources();
  return setInterval(function() {
    return $scope.updateResources();
  }, 60000);
});
