// Generated by CoffeeScript 1.6.3
Rigorix.controller("ListaSfide", function($scope) {
  return console.log("+++++++++");
});

Rigorix.controller("ListaSfide.Sfida", function($scope) {
  $scope.id_avversario = $scope.sfida.id_sfidante === User.id_utente ? $scope.sfida.id_sfidato : $scope.sfida.id_sfidante;
  $scope.risultato = $scope.sfida.risultato.split(",");
  $scope.punti = 0;
  if ($scope.currentUser.id_utente === $scope.sfida.id_vincitore) {
    $scope.punti = 3;
  }
  if ($scope.sfida.id_vincitore === 0) {
    $scope.punti = 1;
  }
  switch ($scope.sfida.stato) {
    case "0":
      return $scope.statoButton = 'lancia_sfida';
    case "1":
      return $scope.statoButton = 'sfida_lanciata';
    case "2":
      return $scope.statoButton = 'vedi_sfida';
    case "3":
      return $scope.statoButton = 'vinta_a_tavolino';
    default:
      return $scope.statoButton = $scope.sfida.stato;
  }
});
