// Generated by CoffeeScript 1.6.3
Rigorix.controller("ListaSfide", function($scope) {
  return true;
});

Rigorix.controller("ListaSfide.Sfida", function($scope) {
  $scope.id_avversario = $scope.sfida.id_sfidante === User.id_utente ? $scope.sfida.id_sfidato : $scope.sfida.id_sfidante;
  $scope.risultato = $scope.sfida.risultato.split(",");
  console.log("date", $scope.sfida.dta_sfida, $scope.sfida.dta_conclusa);
  if ($scope.currentUser.id_utente === $scope.sfida.id_vincitore) {
    $scope.punti = 3;
    $scope.risultatoLabel = "won";
  } else if ($scope.sfida.id_vincitore === 0) {
    $scope.punti = 1;
    $scope.risultatoLabel = "draw";
  } else {
    $scope.punti = 0;
    $scope.risultatoLabel = "lose";
  }
  switch ($scope.sfida.stato) {
    case "0":
      return $scope.statoButton = 'lancia_sfida';
    case "1":
      return $scope.statoButton = $scope.sfida.id_sfidante === User.id_utente ? 'lanciata' : 'rispondi';
    case "2":
      return $scope.statoButton = 'vedi_sfida';
    case "3":
      return $scope.statoButton = 'vinta_a_tavolino';
    default:
      return $scope.statoButton = $scope.sfida.stato;
  }
});
