// Generated by CoffeeScript 1.6.3
Rigorix.controller("Main", function($scope, AuthService) {
  var _this = this;
  $scope.siteTitle = "Website title";
  $scope.userLogged = false;
  $scope.$on("$routeChangeStart", function(event, next, current) {
    if (next.$$route.originalPath === "/logout") {
      return $scope.$emit("LOGOUT");
    }
  });
  $scope.$on("LOGOUT", function() {
    var User;
    User = false;
    $scope.currentUser = null;
    return $scope.userLogged = false;
  });
  if (User !== false) {
    $scope.userLogged = true;
    $scope.currentUser = User;
    AuthService.get({
      action: "game",
      value: "status"
    }, function(json) {
      return $scope.currentUser = json;
    });
    return setInterval(function() {
      return AuthService.get({
        action: "game",
        value: "status"
      }, function(json) {
        return $scope.currentUser = json;
      });
    }, RigorixConfig.updateTime);
  }
});
